server:
  port: 8082

spring:
  application:
    name: hotels-service
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_manage?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/