server:
  port: 8082

spring:
  application:
    name: hotel-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
        group: hotel-example
      config:
        server-addr: nacos-server:8848
        group: hotel-example
        file-extension: yaml
  config:
    import:
      - optional:nacos:hotel-service.yaml
      - optional:nacos:datasource-config.yaml
