server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: rating-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservicesRating
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
