spring:
  cloud:
    gateway:
      routes:
        - id: placeOrder
          uri: lb://hotel-order
          predicates:
            - Path=/order/create
        - id: queryStorage
          uri: lb://hotel-storage
          predicates:
            - Path=/storage/
        - id: queryAccount
          uri: lb://hotel-account
          predicates:
            - Path=/account/
        - id: praiseItemRocketMQ
          uri: lb://hotel-provider
          predicates:
            - Path=/praise/rocketmq
        - id: praiseItemSentinel
          uri: lb://hotel-provider
          predicates:
            - Path=/praise/sentinel
        - id: queryPraise
          uri: lb://hotel-consumer
          predicates:
            - Path=/praise/query
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/hotels/*