version: "3"
services:

  # nacos
  nacos:
    image: nacos/nacos-server:v2.4.2
    hostname: nacos-server
    restart: on-failure
    container_name: hotel-nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"

  # mysql
  mysql:
    container_name: hotel-mysql
    hostname: hotel-mysql
    restart: on-failure
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hotel_storage
    ports:
      - "3306:3306"
    volumes:
      - ../config-init/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      [
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci
      ]

  # rocketMQ
  rmqnamesrv:
    image: apache/rocketmq:4.9.4
    hostname: rocketmq
    restart: on-failure
    container_name: hotel-rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv

  rmqbroker:
    image: apache/rocketmq:4.9.4
    restart: on-failure
    container_name: hotel-rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - ../config-init/rocketmq/broker.conf:/opt/rocketmq-4.9.4/conf/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-4.9.4/conf/broker.conf
    depends_on:
      - rmqnamesrv

  # seata
  seata-server:
    image: seataio/seata-server:1.5.1
    hostname: seata-server
    restart: on-failure
    container_name: hotel-seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
