server:
  port: 30010
spring:
  application:
    name: hotel-gateway
  cloud:
    nacos:
      config:
        server-addr: nacos-server:8848
        group: hotel-example
        file-extension: yaml
      discovery:
        server-addr: nacos-server:8848
        group: hotel-example
  config:
    import: optional:nacos:hotel-gateway.yaml




